Рекомендательная система фильмов

In [1]:
import numpy as np
import pandas as pd
import os
import warnings
warnings.filterwarnings('ignore')

In [27]:
ratings_full_df = pd.read_csv('ratings.csv')
movies_df = pd.read_csv('movies.csv')

In [29]:
movies_df

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
62418,209157,We (2018),Drama
62419,209159,Window of the Soul (2001),Documentary
62420,209163,Bad Poems (2018),Comedy|Drama
62421,209169,A Girl Thing (2001),(no genres listed)
62422,209171,Women of Devil's Island (1962),Action|Adventure|Drama

In [31]:
ratings_full_df

          userId  movieId  rating   timestamp
0              1      296     5.0  1147880044
1              1      306     3.5  1147868817
2              1      307     5.0  1147868828
3              1      665     5.0  1147878820
4              1      899     3.5  1147868510
...          ...      ...     ...         ...
25000090  162541    50872     4.5  1240953372
25000091  162541    55768     2.5  1240951998
25000092  162541    56176     2.0  1240950697
25000093  162541    58559     4.0  1240953434
25000094  162541    63876     5.0  1240952515

[25000095 rows x 4 columns]

In [33]:
ratings_cut_df = ratings_full_df[:200000]
ratings_cut_df

        userId  movieId  rating   timestamp
0            1      296     5.0  1147880044
1            1      306     3.5  1147868817
2            1      307     5.0  1147868828
3            1      665     5.0  1147878820
4            1      899     3.5  1147868510
...        ...      ...     ...         ...
199995    1409    48516     4.0  1287843475
199996    1409    48696     4.0  1287854818
199997    1409    48738     3.5  1287854109
199998    1409    48774     4.0  1287849077
199999    1409    48780     3.0  1287843995

[200000 rows x 4 columns]

In [35]:
mean_user_ratings = ratings_full_df.groupby("userId")["rating"].mean()
mean_user_ratings

userId
1         3.814286
2         3.630435
3         3.697409
4         3.378099
5         3.752475
            ...
162537    4.039604
162538    3.415584
162539    4.510638
162540    3.829545
162541    3.365385
Name: rating, Length: 162541, dtype: float64

In [37]:
ratings_cut_df = ratings_cut_df.merge(mean_user_ratings, how="left", on="userId", suffixes=("", "user_mean"))
ratings_cut_df

#Денормализация данных, для одного пользователя появилось много строк

        userId  movieId  rating   timestamp  ratinguser_mean
0            1      296     5.0  1147880044         3.814286
1            1      306     3.5  1147868817         3.814286
2            1      307     5.0  1147868828         3.814286
3            1      665     5.0  1147878820         3.814286
4            1      899     3.5  1147868510         3.814286
...        ...      ...     ...         ...              ...
199995    1409    48516     4.0  1287843475         3.043624
199996    1409    48696     4.0  1287854818         3.043624
199997    1409    48738     3.5  1287854109         3.043624
199998    1409    48774     4.0  1287849077         3.043624
199999    1409    48780     3.0  1287843995         3.043624

[200000 rows x 5 columns]

In [39]:
mean_movie_ratings = ratings_full_df.groupby("movieId")["rating"].mean()
mean_movie_ratings

movieId
1         3.893708
2         3.251527
3         3.142028
4         2.853547
5         3.058434
            ...
209157    1.500000
209159    3.000000
209163    4.500000
209169    3.000000
209171    3.000000
Name: rating, Length: 59047, dtype: float64

In [41]:
movies_df = movies_df.merge(mean_movie_ratings, how="left", on="movieId").rename({"rating": "rating_movie_mean"}, axis=1)
movies_df

,movieId,title,genres,rating_movie_mean
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,3.893708
1,2,Jumanji (1995),Adventure|Children|Fantasy,3.251527
2,3,Grumpier Old Men (1995),Comedy|Romance,3.142028
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,2.853547
4,5,Father of the Bride Part II (1995),Comedy,3.058434
...,...,...,...,...
62418,209157,We (2018),Drama,1.500000
62419,209159,Window of the Soul (2001),Documentary,3.000000
62420,209163,Bad Poems (2018),Comedy|Drama,4.500000
62421,209169,A Girl Thing (2001),(no genres listed),3.000000
62422,209171,Women of Devil's Island (1962),Action|Adventure|Drama,3.000000

In [43]:
ratings_cut_df

        userId  movieId  rating   timestamp  ratinguser_mean
0            1      296     5.0  1147880044         3.814286
1            1      306     3.5  1147868817         3.814286
2            1      307     5.0  1147868828         3.814286
3            1      665     5.0  1147878820         3.814286
4            1      899     3.5  1147868510         3.814286
...        ...      ...     ...         ...              ...
199995    1409    48516     4.0  1287843475         3.043624
199996    1409    48696     4.0  1287854818         3.043624
199997    1409    48738     3.5  1287854109         3.043624
199998    1409    48774     4.0  1287849077         3.043624
199999    1409    48780     3.0  1287843995         3.043624

[200000 rows x 5 columns]

In [45]:
datetimes = pd.to_datetime(ratings_cut_df["timestamp"], unit='s')

In [47]:
datetimes

0        2006-05-17 15:34:04
1        2006-05-17 12:26:57
2        2006-05-17 12:27:08
3        2006-05-17 15:13:40
4        2006-05-17 12:21:50
                 ...
199995   2010-10-23 14:17:55
199996   2010-10-23 17:26:58
199997   2010-10-23 17:15:09
199998   2010-10-23 15:51:17
199999   2010-10-23 14:26:35
Name: timestamp, Length: 200000, dtype: datetime64[ns]

In [49]:
ratings_cut_df['year'] = datetimes.dt.year
ratings_cut_df['month'] = datetimes.dt.month
ratings_cut_df['day'] = datetimes.dt.day
ratings_cut_df['day_of_week'] = datetimes.dt.day_of_week
ratings_cut_df['hour'] = datetimes.dt.hour

def get_part_of_day(hour):
    if 5 <= hour < 12:
        return 'morning'
    elif 12 <= hour < 17:
        return 'afternoon'
    elif 17 <= hour < 21:
        return 'evening'
    else:
        return 'night'

ratings_cut_df['part_of_day'] = ratings_cut_df['hour'].apply(get_part_of_day) #Применяем функцию get_part.... чтобы уменьшить количество входных данных
#для модели, делаем по сути из числового признака категориальный

ratings_cut_df = pd.get_dummies(ratings_cut_df, columns=['part_of_day'], prefix='time') #OneHot, добавление новых 4 колонок

ratings_cut_df = ratings_cut_df.drop(columns=['timestamp'])  #Выбрасываем timestamp, он нам уже не нужен

ratings_cut_df

,userId,movieId,rating,ratinguser_mean,year,month,day,day_of_week,hour,time_afternoon,time_evening,time_morning,time_night
0,1,296,5.0,3.814286,2006,5,17,2,15,True,False,False,False
1,1,306,3.5,3.814286,2006,5,17,2,12,True,False,False,False
2,1,307,5.0,3.814286,2006,5,17,2,12,True,False,False,False
3,1,665,5.0,3.814286,2006,5,17,2,15,True,False,False,False
4,1,899,3.5,3.814286,2006,5,17,2,12,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,1409,48516,4.0,3.043624,2010,10,23,5,14,True,False,False,False
199996,1409,48696,4.0,3.043624,2010,10,23,5,17,False,True,False,False
199997,1409,48738,3.5,3.043624,2010,10,23,5,17,False,True,False,False
199998,1409,48774,4.0,3.043624,2010,10,23,5,15,True,False,False,False
199999,1409,48780,3.0,3.043624,2010,10,23,5,14,True,False,False,False

In [53]:
genres_list = movies_df['genres'].apply(lambda x : x.split('|'))
genres_list

0        [Adventure, Animation, Children, Comedy, Fantasy]
1                           [Adventure, Children, Fantasy]
2                                        [Comedy, Romance]
3                                 [Comedy, Drama, Romance]
4                                                 [Comedy]
                               ...
62418                                              [Drama]
62419                                        [Documentary]
62420                                      [Comedy, Drama]
62421                                 [(no genres listed)]
62422                           [Action, Adventure, Drama]
Name: genres, Length: 62423, dtype: object

In [57]:
from sklearn.preprocessing import MultiLabelBinarizer

mlb = MultiLabelBinarizer()

mlb.fit(genres_list)

list(mlb.classes_)

['(no genres listed)',
 'Action',
 'Adventure',
 'Animation',
 'Children',
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'IMAX',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western']

In [59]:
mlb.transform(genres_list)

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 1, 1, ..., 0, 0, 0]])

In [61]:
genres_encoded = pd.DataFrame(mlb.transform(genres_list), columns=mlb.classes_, index=movies_df.index)

In [63]:
genres_encoded.head()

,(no genres listed),Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,0,0,1,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0
3,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0
4,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [65]:
movies_encoded = pd.concat([movies_df.drop("genres", axis=1), genres_encoded], axis=1)
movies_encoded.head()

,movieId,title,rating_movie_mean,(no genres listed),Action,Adventure,Animation,Children,Comedy,Crime,...,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),3.893708,0,0,1,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
1,2,Jumanji (1995),3.251527,0,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,Grumpier Old Men (1995),3.142028,0,0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
3,4,Waiting to Exhale (1995),2.853547,0,0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
4,5,Father of the Bride Part II (1995),3.058434,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [67]:
df = ratings_cut_df.merge(movies_encoded, how="left", on="movieId")

In [69]:
df

,userId,movieId,rating,ratinguser_mean,year,month,day,day_of_week,hour,time_afternoon,...,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,296,5.0,3.814286,2006,5,17,2,15,True,...,0,0,0,0,0,0,0,1,0,0
1,1,306,3.5,3.814286,2006,5,17,2,12,True,...,0,0,0,0,0,0,0,0,0,0
2,1,307,5.0,3.814286,2006,5,17,2,12,True,...,0,0,0,0,0,0,0,0,0,0
3,1,665,5.0,3.814286,2006,5,17,2,15,True,...,0,0,0,0,0,0,0,0,1,0
4,1,899,3.5,3.814286,2006,5,17,2,12,True,...,0,0,0,1,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,1409,48516,4.0,3.043624,2010,10,23,5,14,True,...,0,0,0,0,0,0,0,1,0,0
199996,1409,48696,4.0,3.043624,2010,10,23,5,17,False,...,0,0,0,0,0,1,0,0,0,0
199997,1409,48738,3.5,3.043624,2010,10,23,5,17,False,...,0,0,0,0,0,0,0,1,0,0
199998,1409,48774,4.0,3.043624,2010,10,23,5,15,True,...,0,0,0,0,0,0,1,1,0,0
199999,1409,48780,3.0,3.043624,2010,10,23,5,14,True,...,0,0,0,0,1,0,1,1,0,0

In [73]:
mean_genres_by_users = pd.concat(
    [
        df["userId"],
        df[list(mlb.classes_)].multiply(df["rating"], axis=0)
    ], axis=1
).groupby("userId").mean()

mean_genres_by_users

,(no genres listed),Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
userId,,,,,,,,,,,,,,,,,,,,
1,0.000000,0.235714,0.585714,0.114286,0.164286,1.271429,0.464286,0.028571,2.928571,0.257143,0.050000,0.050000,0.000000,0.264286,0.200000,1.071429,0.264286,0.307143,0.278571,0.035714
2,0.000000,1.326087,1.592391,0.334239,0.497283,1.135870,0.307065,0.000000,1.766304,0.627717,0.000000,0.065217,0.154891,0.195652,0.160326,0.584239,0.611413,0.625000,0.279891,0.067935
3,0.005335,1.853659,1.113567,0.303354,0.271341,0.926829,0.782012,0.014482,1.375762,0.444360,0.032774,0.243140,0.461128,0.032774,0.355945,0.323171,1.262195,1.345274,0.146341,0.045732
4,0.000000,1.909091,1.448347,0.444215,0.371901,1.208678,0.607438,0.084711,0.758264,0.456612,0.000000,0.130165,0.411157,0.105372,0.283058,0.142562,1.111570,0.820248,0.123967,0.105372
5,0.000000,0.663366,0.801980,0.148515,0.297030,1.732673,0.574257,0.000000,1.702970,0.277228,0.000000,0.138614,0.118812,0.257426,0.326733,0.702970,0.445545,0.950495,0.089109,0.148515
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1405,0.000000,0.388448,0.297848,0.074745,0.135900,1.556059,0.593431,0.073613,2.151755,0.235561,0.106455,0.148358,0.006795,0.245753,0.272933,0.919592,0.177803,0.652322,0.199320,0.074745
1406,0.000000,0.409091,0.409091,0.454545,0.454545,1.590909,1.318182,0.000000,2.500000,0.000000,0.000000,0.409091,0.000000,0.000000,0.545455,0.590909,0.409091,1.000000,0.863636,0.000000
1407,0.000000,0.539062,0.562500,0.132812,0.320312,2.914062,0.398438,0.023438,0.859375,0.351562,0.015625,0.125000,0.000000,0.343750,0.187500,0.953125,0.304688,0.343750,0.195312,0.156250
1408,0.000000,1.404762,0.761905,0.000000,0.119048,1.523810,1.071429,0.000000,2.476190,0.214286,0.095238,0.309524,0.119048,0.000000,0.214286,1.238095,0.309524,1.714286,0.428571,0.190476
1409,0.000000,1.196970,0.776292,0.120321,0.163993,0.962567,0.636364,0.000000,1.518717,0.262923,0.020499,0.068627,0.045455,0.059715,0.199643,0.514260,0.340463,0.899287,0.386809,0.176471

In [75]:
df = df.merge(mean_genres_by_users, how='left', on="userId", suffixes=("", "mean_gen"))
df

,userId,movieId,rating,ratinguser_mean,year,month,day,day_of_week,hour,time_afternoon,...,Film-Noirmean_gen,Horrormean_gen,IMAXmean_gen,Musicalmean_gen,Mysterymean_gen,Romancemean_gen,Sci-Fimean_gen,Thrillermean_gen,Warmean_gen,Westernmean_gen
0,1,296,5.0,3.814286,2006,5,17,2,15,True,...,0.050000,0.050000,0.000000,0.264286,0.200000,1.071429,0.264286,0.307143,0.278571,0.035714
1,1,306,3.5,3.814286,2006,5,17,2,12,True,...,0.050000,0.050000,0.000000,0.264286,0.200000,1.071429,0.264286,0.307143,0.278571,0.035714
2,1,307,5.0,3.814286,2006,5,17,2,12,True,...,0.050000,0.050000,0.000000,0.264286,0.200000,1.071429,0.264286,0.307143,0.278571,0.035714
3,1,665,5.0,3.814286,2006,5,17,2,15,True,...,0.050000,0.050000,0.000000,0.264286,0.200000,1.071429,0.264286,0.307143,0.278571,0.035714
4,1,899,3.5,3.814286,2006,5,17,2,12,True,...,0.050000,0.050000,0.000000,0.264286,0.200000,1.071429,0.264286,0.307143,0.278571,0.035714
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,1409,48516,4.0,3.043624,2010,10,23,5,14,True,...,0.020499,0.068627,0.045455,0.059715,0.199643,0.514260,0.340463,0.899287,0.386809,0.176471
199996,1409,48696,4.0,3.043624,2010,10,23,5,17,False,...,0.020499,0.068627,0.045455,0.059715,0.199643,0.514260,0.340463,0.899287,0.386809,0.176471
199997,1409,48738,3.5,3.043624,2010,10,23,5,17,False,...,0.020499,0.068627,0.045455,0.059715,0.199643,0.514260,0.340463,0.899287,0.386809,0.176471
199998,1409,48774,4.0,3.043624,2010,10,23,5,15,True,...,0.020499,0.068627,0.045455,0.059715,0.199643,0.514260,0.340463,0.899287,0.386809,0.176471
199999,1409,48780,3.0,3.043624,2010,10,23,5,14,True,...,0.020499,0.068627,0.045455,0.059715,0.199643,0.514260,0.340463,0.899287,0.386809,0.176471

In [79]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.drop(["rating", "title"], axis=1), df["rating"], test_size=0.2, random_state=42)

In [87]:
def naive_approach(X_train, y_mean, movieId):
    movie_data = X_train[X_train["movieId"]==movieId]
    if movie_data.empty:
        return y_mean
    else:
        return movie_data.iloc[0]["rating_movie_mean"]

In [89]:
y_mean = y_train.mean()
predict = [naive_approach(X_train, y_mean, movieId) for movieId in X_test["movieId"]]

predict

[3.5701620505454055,
 3.7648009950248755,
 3.30687887203589,
 2.992050660199407,
 3.6987526802388584,
 4.413576004516335,
 3.453398738612474,
 4.151341616415071,
 2.9386574074074074,
 3.4711328976034856,
 3.6686106507395477,
 2.972902097902098,
 3.995328608247423,
 3.2634129456559364,
 4.1805253650920005,
 4.237947624243627,
 4.114713689799014,
 3.6224948492227007,
 2.748033877797943,
 4.284353213163313,
 3.5569092991773403,
 3.817136507193824,
 4.014331931413782,
 3.586023142509135,
 3.4105008077544428,
 3.6222502851556135,
 3.185682326621924,
 3.8968066922200353,
 3.508920477209269,
 3.3279432064681522,
 3.44905273937532,
 4.04407206509105,
 2.993827160493827,
 3.2194312796208533,
 3.8756302521008403,
 2.886744743146127,
 4.129097007632781,
 3.183039195863782,
 4.0903399807075225,
 3.859743262873914,
 4.212267265284564,
 2.6973419250906163,
 3.804476930105071,
 3.356494275562574,
 3.6402393970740357,
 3.379296875,
 3.332691196301291,
 3.182581786030062,
 4.077005923532579,
 3.1024590163934427,
 3.8578206757915274,
 3.7256878529376425,
 3.7629512767830935,
 3.6809198555552447,
 2.869921875,
 3.736804328621908,
 3.3279432064681522,
 3.63714378238342,
 3.3553571428571427,
 4.004931687002265,
 4.413576004516335,
 4.042453118318979,
 3.089685637970002,
 3.566753125,
 3.810891994253624,
 3.0618285987109095,
 3.9223771740001605,
 4.151341616415071,
 3.183039195863782,
 3.21253534401508,
 3.684585792929628,
 3.566753125,
 3.6551898004754015,
 4.063324170351779,
 3.7629512767830935,
 3.7212436096910424,
 3.8866075594960336,
 4.043698962701391,
 3.075899843505477,
 3.6441499676793794,
 4.115838373930576,
 3.982837478764647,
 4.188912039361382,
 3.77259521253079,
 2.5938388625592417,
 3.1337579617834397,
 3.832474226804124,
 3.5416914014338556,
 3.6099000908265215,
 3.678158491145853,
 3.6151245126899516,
 3.554780876494024,
 3.7440284321018265,
 3.559661183402897,
 3.4016470905899823,
 3.126992778307671,
 3.5271542360608255,
 3.4299137931034482,
 3.867109990883252,
 3.7958638583638584,
 4.052931292008962,
 3.2715539947322214,
 3.381151887993212,
 3.6447072072072073,
 3.7486744432661716,
 3.9386049061258053,
 2.945538057742782,
 3.387031840917409,
 3.8237068028689416,
 4.027935943060498,
 4.093231050865188,
 3.3090128755364807,
 3.7905082491792377,
 3.683260267651131,
 3.9678439327049277,
 3.2346062591797535,
 3.7316413875957353,
 2.3533487297921476,
 3.5614250614250613,
 3.5007030550939535,
 3.3468825875823796,
 3.302920603755062,
 2.771714922048998,
 3.1678994082840237,
 3.9610988664987405,
 3.6189967589864467,
 3.3759493670886074,
 3.9721584270115637,
 3.119301648884578,
 3.8283514492753623,
 3.7397893655278707,
 3.7374912526242126,
 3.9743764824265075,
 3.2450275842044136,
 3.746882535308302,
 3.0315704574259708,
 3.3493975903614457,
 3.862846830588766,
 3.6251903746573255,
 3.642062742629315,
 3.2380838259572884,
 3.7905082491792377,
 4.107364341085272,
 4.083479216009336,
 2.6065573770491803,
 3.9743764824265075,
 3.7075786662215173,
 3.6550684931506847,
 3.546082949308756,
 3.4367939112855272,
 1.626425855513308,
 3.566753125,
 3.642556818181818,
 2.705886421802587,
 2.9808583737797893,
 3.782392095253845,
 3.6524786324786325,
 3.778046421663443,
 3.5271542360608255,
 3.6317144959529064,
 3.2784747236368155,
 2.725897255453906,
 2.8429584599797364,
 3.373931536542473,
 3.87355561527172,
 3.6545932715342153,
 3.458824760974248,
 3.810891994253624,
 3.279727095516569,
 3.9538763988305274,
 3.678158491145853,
 3.471868720696584,
 3.94637410899458,
 2.5814764286797027,
 3.4694789622847177,
 4.063227503693827,
 3.373931536542473,
 3.9057678412037236,
 3.3549243168861804,
 4.124754805806199,
 3.3461399057629575,
 3.490556978233035,
 3.0375881523272215,
 3.540186659346692,
 3.324559696409458,
 2.442042042042042,
 3.9679004101879234,
 3.0770631067961167,
 3.473856209150327,
 4.147655276621689,
 2.562396694214876,
 3.982837478764647,
 3.5759786219846887,
 3.362146487684087,
 3.521276595744681,
 3.4454764776839566,
 3.7256878529376425,
 3.394530860504537,
 3.107188160676533,
 3.402909447531873,
 3.566753125,
 3.6809198555552447,
 3.4069031965540693,
 3.5082304526748973,
 3.3373015873015874,
 2.637077181835171,
 3.859743262873914,
 3.9112629219981203,
 2.895021645021645,
 3.713415719933046,
 3.506566659749192,
 4.0791663372598626,
 3.701492537313433,
 3.04296875,
 4.215804447106386,
 3.8276647771479384,
 2.7942023026315788,
 3.475467868105753,
 3.9771659707724427,
 4.009751032903046,
 3.5177253478523896,
 3.9721584270115637,
 4.166538211421277,
 3.436047876085426,
 3.183039195863782,
 3.6803611738148985,
 3.5480708412397215,
 2.7609040814420474,
 3.3538338658146967,
 3.4586751747189304,
 3.4850415512465376,
 3.005938242280285,
 3.324559696409458,
 3.948806325713417,
 3.695939274253271,
 2.6421677802524126,
 3.4337848766680144,
 3.487783595113438,
 2.638095238095238,
 3.581858407079646,
 3.2593627146699773,
 3.2168744804655027,
 3.919385562176419,
 3.95171909290417,
 2.72247882986913,
 3.3863104638240626,
 3.4504284772577454,
 3.9342721173349977,
 2.6559040590405902,
 3.92903168068731,
 3.9699857074797524,
 3.9332307440897702,
 3.9960093896713613,
 3.566753125,
 3.739861235452104,
 3.2422947422947423,
 3.987891317188423,
 3.189445196211096,
 3.875756048387097,
 2.8716600752387382,
 3.141875423155044,
 3.458824760974248,
 3.8339767227471766,
 3.232330827067669,
 3.4035752025361043,
 3.76906584992343,
 3.088307641849787,
 3.7985794157918757,
 3.1304380270129095,
 3.854908898649748,
 3.860718611223254,
 4.041666666666667,
 3.141875423155044,
 2.6559040590405902,
 3.282000241283629,
 2.704717530576587,
 3.985201012978791,
 3.834885361552028,
 2.9703603907039406,
 3.6126005361930296,
 3.87355561527172,
 3.663023497442455,
 3.2168744804655027,
 3.566753125,
 3.2515271586594023,
 3.7347471953281084,
 3.6402393970740357,
 2.731730252552391,
 2.7275565964090553,
 3.6162405303030303,
 4.039633147723551,
 3.962089077412513,
 3.4367939112855272,
 4.151341616415071,
 3.0007246376811594,
 3.7289104638619204,
 3.2755446308077887,
 4.049196669403073,
 3.9332307440897702,
 3.566753125,
 3.569155800809933,
 3.2275993972412196,
 3.30687887203589,
 3.8577375377250496,
 4.154341841841842,
 3.566753125,
 3.345524542829644,
 4.155508420105412,
 3.566753125,
 3.215840517241379,
 3.753526354862658,
 3.566753125,
 3.677304434479322,
 3.141875423155044,
 4.2617585117585115,
 3.782258064516129,
 2.5814764286797027,
 3.7985794157918757,
 3.2840766612932115,
 3.739115002366304,
 3.738303007797995,
 3.71598995395563,
 3.8633714825703485,
 3.169642857142857,
 3.102854287948562,
 2.913390570869107,
 2.6377331420373027,
 3.506566659749192,
 3.5756617647058824,
 4.027754084377666,
 3.680610122486711,
 2.781758208039276,
 3.854908898649748,
 4.115057915057915,
 3.4016470905899823,
 3.566753125,
 3.8543626499427606,
 3.424043062200957,
 4.2617585117585115,
 3.391284174459276,
 4.050986691142726,
 3.884479717813051,
 3.5416914014338556,
 3.3372789177825513,
 2.8108767648596826,
 4.044107902443195,
 3.668711656441718,
 2.775118358758548,
 3.8419396832284662,
 3.5519610870907967,
 3.49023694602896,
 3.7448006932409013,
 3.908041554444017,
 3.985201012978791,
 2.862689393939394,
 3.265695437053326,
 3.169642857142857,
 3.5054833321228847,
 3.350841659915384,
 4.228310618821568,
 4.284353213163313,
 3.768890283005716,
 3.7008196721311477,
 4.158633114773465,
 4.035884291468327,
 2.0106516290726817,
 4.413576004516335,
 3.2644248782315475,
 3.593611584327087,
 3.369318986266459,
 2.7942023026315788,
 4.413576004516335,
 3.8345168653309663,
 3.018651362984218,
 3.7548282627709617,
 3.121140142517815,
 3.9386811582447887,
 3.2537871703759116,
 3.2755446308077887,
 2.964968752944132,
 3.78961419221495,
 3.488830486202365,
 3.4593995223473217,
 3.8543626499427606,
 4.142049808429118,
 3.921667748817364,
 4.247579083279535,
 3.725545950864422,
 3.5323234102518937,
 4.284353213163313,
 2.9372215891432716,
 3.456673093401885,
 3.3194638694638696,
 2.876852832186342,
 4.166538211421277,
 3.853819139596137,
 3.369268791545935,
 3.8436431014823262,
 3.183039195863782,
 3.760454265340259,
 3.316268486916951,
 3.715354676022366,
 3.384297520661157,
 2.58675799086758,
 3.3843505768515074,
 3.805669679539852,
 3.759075907590759,
 4.0903399807075225,
 3.8347800805748222,
 3.567504928339283,
 3.2207120980091886,
 3.6674553101997898,
 3.038846380223661,
 2.833935833709896,
 4.2186616007543405,
 4.072563683103529,
 3.461859688195991,
 2.921479069028517,
 4.066350639578631,
 3.7314432989690722,
 3.572959457045901,
 4.0278640874010225,
 3.326568919110356,
 3.6176470588235294,
 3.6682604735883424,
 3.3959039739590398,
 3.6987526802388584,
 2.52094395280236,
 3.781831019063309,
 3.0442727957799547,
 3.994722955145119,
 3.684536463628801,
 3.0018543492919756,
 4.1400006419103255,
 4.155508420105412,
 3.496595698692316,
 4.009751032903046,
 2.9788651669293595,
 3.218143203883495,
 2.7501075885812654,
 3.6125356125356127,
 3.077245421955237,
 3.2535470310036785,
 3.8232229317240893,
 3.566753125,
 3.87355561527172,
 2.5242192479286167,
 3.8001710654936462,
 3.6019247594050743,
 3.130988477865373,
 3.94637410899458,
 3.393713204373423,
 4.111421282646425,
 3.70209666181035,
 3.3622776319626713,
 3.5614250614250613,
 3.6811163895486936,
 4.032858814352574,
 2.875,
 3.566753125,
 3.3260926459042137,
 3.6012122426489004,
 4.115838373930576,
 2.8360270915108137,
 3.569155800809933,
 4.092293699832535,
 3.6001411148069753,
 3.4069031965540693,
 3.559193121693122,
 3.4786404531822726,
 3.2337121506966606,
 3.261860751694393,
 3.4786404531822726,
 3.9152097902097904,
 3.636688379911746,
 3.481373292867982,
 2.5814764286797027,
 3.185315237118283,
 4.003922378199835,
 3.566753125,
 3.7699454046390977,
 3.694101235552013,
 3.2158277343319748,
 3.494191674733785,
 2.8179859989229943,
 3.7256878529376425,
 4.063227503693827,
 3.469360086767896,
 3.985201012978791,
 4.247579083279535,
 3.16412213740458,
 3.4238588415803606,
 3.532892426548051,
 2.8772434974565697,
 2.148764918123786,
 3.6189967589864467,
 3.399880974180553,
 3.310567296996663,
 3.566753125,
 3.66378901931884,
 3.566753125,
 3.736804328621908,
 3.8032886723507917,
 3.1737825216811206,
 3.867109990883252,
 3.3865256946151954,
 3.2530893994979726,
 2.4625850340136055,
 3.566753125,
 4.0278640874010225,
 3.680228941147194,
 3.7256878529376425,
 3.0795249549007817,
 3.922674418604651,
 3.893707794587238,
 3.7858622475401345,
 3.728211826169556,
 2.4079754601226995,
 3.834885361552028,
 3.038320834095482,
 3.5769622833843018,
 3.855033756213369,
 3.4284490812830892,
 3.2023346303501947,
 3.7274175756832943,
 3.469776571791467,
 3.183039195863782,
 3.3079096045197742,
 4.023482769136932,
 3.8179903546792016,
 3.14445727482679,
 4.144122313069856,
 3.759075907590759,
 3.685631629701061,
 3.6170499021526417,
 3.5759786219846887,
 4.042453118318979,
 3.7280957943925235,
 4.014331931413782,
 2.5917225950783,
 2.9479166666666665,
 4.044107902443195,
 3.890470852017937,
 3.4016470905899823,
 3.35157435508346,
 3.566753125,
 3.957920792079208,
 2.6486880466472305,
 3.304147465437788,
 3.8524278803081886,
 3.876533550325488,
 2.8223054515189347,
 3.4993894441680613,
 3.6987526802388584,
 3.3619791666666665,
 2.705886421802587,
 3.9332307440897702,
 3.6751193317422435,
 3.775382785788613,
 3.446133294822731,
 3.702873563218391,
 2.8404558404558404,
 3.893707794587238,
 3.2055174579908914,
 2.8652335902399826,
 4.1805253650920005,
 3.1812899966318624,
 3.94637410899458,
 3.739861235452104,
 4.1270905474103,
 2.5953703703703703,
 3.044989775051125,
 4.048011436845787,
 3.723110151187905,
 3.798284823284823,
 3.210894684714427,
 3.7548282627709617,
 3.726025958751628,
 3.3687002652519893,
 4.0680511556963515,
 3.9538763988305274,
 3.498943045237664,
 3.300373134328358,
 3.678158491145853,
 3.5279255319148937,
 4.092687653868315,
 3.1145833333333335,
 3.282000241283629,
 3.398854961832061,
 3.8111395312418437,
 3.960027567195038,
 3.219017015993573,
 3.6791749812920926,
 4.212267265284564,
 3.9057678412037236,
 2.8360270915108137,
 3.732256203115984,
 3.78390063134779,
 3.9344343517753924,
 3.2890995260663507,
 4.0278640874010225,
 4.2186616007543405,
 3.2880989180834623,
 4.206563778356267,
 3.4474861010394005,
 2.3855534709193247,
 3.127016129032258,
 4.044107902443195,
 3.860718611223254,
 4.212267265284564,
 3.141000094885663,
 3.8179903546792016,
 3.783409773841531,
 3.69532003859762,
 3.3242865137101285,
 3.996512919496695,
 3.7555582702174446,
 3.6791749812920926,
 2.667684996605567,
 3.412776934749621,
 3.683260267651131,
 4.284353213163313,
 3.3642412231030576,
 3.908041554444017,
 3.780095191055633,
 3.4483870967741934,
 3.1304380270129095,
 3.739115002366304,
 4.092293699832535,
 3.2010862700517873,
 4.247579083279535,
 2.7995211310428703,
 2.9984304369663484,
 2.7995211310428703,
 3.683810422564748,
 3.832616788129817,
 3.2688172043010755,
 3.1937196905935634,
 3.6123642439431913,
 4.196617210682493,
 4.078099576960625,
 3.9713489353153877,
 3.7066231000807695,
 3.9669923422233957,
 3.547347362181387,
 3.373931536542473,
 3.132062978222484,
 4.154099127610975,
 3.854908898649748,
 2.391891891891892,
 3.3372789177825513,
 3.265695437053326,
 3.506826414042909,
 3.5617795622328714,
 3.636688379911746,
 4.154099127610975,
 3.4504284772577454,
 3.339492753623188,
 3.823092998955068,
 3.92903168068731,
 4.095140098147855,
 3.5006235909243535,
 3.4994205537850256,
 2.1740901683867464,
 2.9808583737797893,
 3.7699454046390977,
 3.4016470905899823,
 3.8926312460468058,
 3.3173794976238966,
 3.5841487279843443,
 3.481247881458525,
 3.6791749812920926,
 3.9669923422233957,
 4.107340423550448,
 4.076437847866419,
 3.664388396868181,
 2.7103059581320452,
 3.507638565440149,
 3.69532003859762,
 3.857756827949536,
 3.893707794587238,
 3.508920477209269,
 4.063227503693827,
 4.123923182441701,
 3.0,
 4.048011436845787,
 3.6392326732673266,
 3.588040006723819,
 3.854885151495321,
 3.211442786069652,
 3.9688961440042356,
 3.5221202003338896,
 2.792260930558803,
 4.114713689799014,
 3.6843525179856114,
 3.4828125,
 3.6189967589864467,
 3.0209150326797385,
 2.391414554374489,
 3.40623288921336,
 3.6958829205532324,
 3.919385562176419,
 3.7966388225934766,
 2.8379888268156424,
 4.041961756373937,
 3.9635849882596412,
 3.9737302977232924,
 3.6571705198920315,
 1.8678756476683938,
 4.120821574161179,
 3.7066231000807695,
 3.7329878323569177,
 3.4465408805031448,
 4.0278640874010225,
 3.7676258992805756,
 3.0170906200317966,
 3.9161966156325545,
 3.566753125,
 3.44905273937532,
 2.354330708661417,
 4.188912039361382,
 2.8979267166170586,
 3.666639263400197,
 3.996512919496695,
 3.9016070842899313,
 3.9334735998396955,
 4.014331931413782,
 3.2779854620976114,
 3.133744855967078,
 3.7212436096910424,
 3.780095191055633,
 3.4993894441680613,
 3.8578206757915274,
 3.2706855791962175,
 3.2240022712524334,
 2.9202185792349726,
 3.2577711853476075,
 2.7651195499296763,
 3.764014949279231,
 3.2380838259572884,
 3.2922195416164053,
 4.200392285060477,
 3.2634129456559364,
 3.6323874427438274,
 2.5852842809364547,
 4.03,
 4.243014062405697,
 3.834885361552028,
 3.569155800809933,
 4.0885985748218525,
 2.3926359256710255,
 3.707471264367816,
 3.7905082491792377,
 4.151341616415071,
 3.326568919110356,
 3.736804328621908,
 2.6982864137086904,
 3.778046421663443,
 3.304844948089842,
 3.625320662313433,
 4.284353213163313,
 4.155508420105412,
 4.284353213163313,
 3.33851030110935,
 3.5426376440460947,
 3.787694974003466,
 4.072966846132049,
 4.111421282646425,
 4.007664971082154,
 2.7769709543568464,
 3.1505580122130974,
 4.0433978262545285,
 4.147655276621689,
 3.614030819140308,
 3.219017015993573,
 2.91701122268163,
 3.5221202003338896,
 4.2,
 4.146440635556112,
 3.3126619770455386,
 4.011419068736142,
 3.1486119807973285,
 3.338609532138172,
 3.881956462337189,
 3.582624387728796,
 3.010046367851623,
 4.247579083279535,
 3.563234542667348,
 3.5519610870907967,
 3.7274789371354506,
 3.9478244127839814,
 3.5101652454593633,
 3.4989462592202316,
 3.373931536542473,
 3.469776571791467,
 3.9721584270115637,
 3.5358059914407987,
 3.6826059555695605,
 3.2337121506966606,
 4.140194489465154,
 2.9797535211267605,
 3.5007030550939535,
 2.9644052044609666,
 2.178370066632496,
 3.5290399606713954,
 3.5221202003338896,
 3.4271955450063905,
 3.653300431832202,
 3.8187326869806095,
 4.027754084377666,
 3.806483027267668,
 3.566753125,
 3.738263445761167,
 4.151341616415071,
 3.566753125,
 3.7548282627709617,
 3.775382785788613,
 3.7730917580186762,
 4.091188818716808,
 3.17590206185567,
 3.738263445761167,
 3.112239715591671,
 3.0792610250297976,
 3.0862018023341706,
 3.2779854620976114,
 3.779828411811652,
 3.2408267020335986,
 3.723110151187905,
 2.828042328042328,
 3.566753125,
 3.8032886723507917,
 3.6809198555552447,
 3.2055174579908914,
 4.0531350852927615,
 3.128074747346342,
 4.004931687002265,
 3.9610988664987405,
 3.16785290628707,
 3.8207831325301207,
 3.0113916256157633,
 2.3768382352941178,
 3.068421052631579,
 3.2823624595469254,
 4.124787164374591,
 4.042453118318979,
 4.0791663372598626,
 2.9764170459247,
 3.5756617647058824,
 4.228310618821568,
 3.2337121506966606,
 3.981408706166868,
 4.079055441478439,
 4.066310160427808,
 2.0795168595873177,
 3.80918961447679,
 3.3334728033472802,
 2.9461444308445532,
 4.144122313069856,
 3.569032419576918,
 3.566753125,
 2.8555555555555556,
 2.316724436741768,
 3.6791749812920926,
 3.599251506115743,
 3.4847839318320144,
 3.1386393659180976,
 3.990523882896764,
 3.847214137214137,
 2.9808583737797893,
 3.566753125,
 3.932246998284734,
 3.071411568674125,
 3.7892121309802027,
 3.4069031965540693,
 2.509899383317105,
 3.42649120757142,
 2.3285864978902953,
 2.704717530576587,
 3.6408326781234788,
 3.6686106507395477,
 3.8654259126700072,
 3.6813725490196076,
 3.146056782334385,
 3.1083543029693006,
 3.8524278803081886,
 3.9012738853503186,
 3.7892121309802027,
 3.547169811320755,
 3.4163203442037844,
 4.007664971082154,
 3.8318020282569125,
 4.033357053904999,
 2.662490211433046,
 3.750595862331967,
 3.672884440400364,
 2.96875,
 3.616883116883117,
 3.7985794157918757,
 3.768890283005716,
 3.972340425531915,
 3.5551782682512734,
 3.7548282627709617,
 3.6131449368443587,
 3.8517025089605736,
 2.7098591549295774,
 3.842865100733451,
 4.026144852224748,
 2.7395209580838324,
 3.2530893994979726,
 2.837573385518591,
 3.739861235452104,
 3.3494235398454326,
 2.782246376811594,
 3.245164960182025,
 3.4694789622847177,
 3.481247881458525,
 3.2206611570247934,
 3.4922731744774795,
 3.23,
 3.713,
 4.158633114773465,
 3.6012122426489004,
 3.9713489353153877,
 4.000883818094167,
 2.964968752944132,
 1.4841269841269842,
 3.327336331834083,
 3.994798000270234,
 3.9334735998396955,
 3.728033894885504,
 2.330945558739255,
 3.7708333333333335,
 3.4271955450063905,
 3.9721584270115637,
 4.069599241166706,
 3.3807445868316393,
 4.2186616007543405,
 3.7699454046390977,
 2.949264705882353,
 3.254008245533669,
 3.381151887993212,
 4.048011436845787,
 3.893707794587238,
 3.19796903942842,
 3.0186915887850465,
 3.6809198555552447,
 3.2515271586594023,
 3.263863773357444,
 3.8333333333333335,
 3.8578206757915274,
 4.048011436845787,
 4.016746960311998,
 3.9923513986013988,
 2.897867564534231,
 3.9679004101879234,
 4.138093788063338,
 4.129097007632781,
 3.1851045296167246,
 3.908775143429875,
 3.21253534401508,
 3.990523882896764,
 3.7867504835589942,
 3.1362475163213173,
 3.8216216216216217,
 3.5142276422764227,
 3.0698558281245094,
 3.519487750556793,
 3.566753125,
 4.120188599618726,
 3.540186659346692,
 3.1209853445587776,
 3.7019417475728154,
 3.5976107666717074,
 3.681317204301075,
 3.0116109295696307,
 3.496595698692316,
 2.964968752944132,
 3.8654379847719347,
 3.7012564249000572,
 3.566753125,
 3.9546247818499127,
 3.996512919496695,
 3.381151887993212,
 3.5595393307257712,
 3.9713489353153877,
 3.993678056738874,
 3.951473486205661,
 3.42145763311516,
 3.0751429349305743,
 3.3526841448189764,
 3.074168797953964,
 3.1860226104830422,
 3.4069031965540693,

In [95]:
def get_recommendation(X_train, y_mean, userId, movieId):
    movie_data = X_train[X_train["movieId"]==movieId]
    if movie_data.empty:
        return y_mean

    user_data = X_test[X_test["userId"]==userId].iloc[0]
    movie_mean_rating = movie_data.iloc[0]["rating_movie_mean"]
    user_mean_rating = user_data["ratinguser_mean"]

    final_score = (0.5 * movie_mean_rating) + (0.5 * user_mean_rating)
    return final_score

In [97]:
predict = [get_recommendation(X_train, y_mean, userId, movieId) for userId, movieId in zip(X_test["userId"], X_test["movieId"])]
predict

[3.283288910577362,
 3.7415554270899025,
 2.988074852684612,
 2.9649142189885924,
 3.48639557088866,
 4.288788002258167,
 3.7627163184587795,
 3.819314876004146,
 3.426603530493542,
 3.766563753383953,
 3.6646624682269167,
 3.102752187711066,
 3.927664304123711,
 3.381706472827968,
 3.919210050967053,
 4.007403564187929,
 3.7585402768521696,
 3.6444176790144818,
 3.0400685994155765,
 3.9003066878824697,
 3.418042750275169,
 3.545587484366143,
 3.8099915185324438,
 3.366966555177397,
 3.558753588590597,
 4.061125142577807,
 3.2588928238275674,
 3.8821094163975576,
 3.8556999080261223,
 3.210003349265822,
 3.6818011964774984,
 3.814893175402668,
 3.3549382716049383,
 3.4584199081031093,
 3.6742021123517903,
 2.913886800682223,
 3.9395485038163907,
 2.9478414370123507,
 3.9674672876510586,
 3.8022854245404054,
 3.904744743753393,
 3.3322152663427764,
 3.639307430569777,
 3.7859454270503385,
 3.4364208372970344,
 3.3059495762600166,
 3.197654009365599,
 3.0231794379066717,
 3.8776875597277844,
 3.6546777840587903,
 3.417685848099845,
 3.665596220046803,
 3.5226046706496112,
 3.8034228907405856,
 2.903849826388889,
 3.7015724187140853,
 2.959680558457957,
 3.4705542700463354,
 3.5759836561743343,
 4.263576954612244,
 3.835359430829596,
 4.050796451632608,
 3.5245725487147306,
 3.566753125,
 3.571497657643417,
 3.7928190612602166,
 3.2568975422239608,
 4.089369438344522,
 3.193581453601994,
 3.35626767200754,
 3.4648735416261043,
 3.566753125,
 3.285928233571034,
 3.32737104039977,
 3.661208648100285,
 3.5662431066206692,
 3.900355061799299,
 3.9789007634019775,
 3.503467163132049,
 3.6100749838396897,
 3.7128561617552043,
 4.106283604247189,
 3.976631246266794,
 3.761297606265395,
 3.1079895419807277,
 2.8625879361156006,
 3.1923454877862985,
 3.6499997792667767,
 3.5315125454132605,
 3.420711898634151,
 3.659124756344976,
 3.584905775670325,
 3.714321908358605,
 2.642887916542213,
 3.543131237602683,
 3.4268438467809546,
 3.190139618030413,
 3.7930986795807256,
 3.8662473031339335,
 3.7847740344450873,
 3.701997560898098,
 3.257041007328751,
 3.801687055107717,
 3.750925032175032,
 3.4279086502045146,
 3.635354113579508,
 3.0040774400863444,
 3.8379009471966725,
 3.5031995552806245,
 3.612019919582197,
 4.264948858765927,
 3.2757704477308804,
 3.6212428251545905,
 3.621363143534303,
 4.100426820721395,
 3.763407025693773,
 3.798404963460789,
 2.7680205187422278,
 3.278487011424697,
 3.750351527546977,
 3.5046999383278425,
 3.8335498541163373,
 3.002158599784516,
 3.2405218690904656,
 3.66018168218855,
 3.9171966687622746,
 3.626330847927865,
 3.803708392837089,
 3.175951963202306,
 3.387321504688832,
 3.613525256012343,
 3.633783220297069,
 3.5520616589347727,
 3.1598701139412873,
 3.5475742156310295,
 3.2488933368210935,
 3.4909239607436366,
 3.8116077470916183,
 3.675802734498474,
 3.4618610656378017,
 3.2626229940597256,
 3.2272699348662988,
 3.7900691568440057,
 3.802933637855414,
 3.6341442921692373,
 3.6352860673002105,
 3.6580750473964727,
 3.6386043572764493,
 3.389342613414395,
 3.6368366719548204,
 2.957597954494622,
 3.566753125,
 2.9318226267779837,
 3.1110732922021063,
 3.323599441293026,
 3.6084484437930566,
 3.562626302540686,
 3.6626388460108745,
 3.603697781680488,
 3.43215838673647,
 3.32207318271393,
 3.1867828246181444,
 3.0427432399525083,
 3.4342483769668886,
 3.5761220699309417,
 3.84616456029541,
 3.2896057021039957,
 3.6110672989019603,
 3.462444192919575,
 3.7198627277171505,
 3.7962221027157836,
 3.296279187934499,
 3.622042016329351,
 2.996383375630174,
 3.374327581828858,
 3.7977576632860277,
 3.3350635943581928,
 3.4735735757742754,
 3.6716482049547183,
 4.222377402903099,
 3.61142611726504,
 3.3145555975502523,
 3.1350952149236275,
 3.8360507764818568,
 3.425375086299967,
 2.86060912170752,
 3.811331157474914,
 3.4080967707893626,
 3.6186848613319205,
 4.209792550591546,
 2.9024623570700783,
 3.9484700214336055,
 3.3192977222072977,
 3.4992550620238614,
 3.8683365871413917,
 3.508145964163867,
 3.500403735081261,
 3.5075888133368456,
 3.3214512231954094,
 3.4750703589450893,
 3.566753125,
 3.5964840241631646,
 3.506277151102587,
 3.83225700936645,
 3.568650793650794,
 3.025658332017909,
 3.7033615643228632,
 3.8370268098362694,
 3.2597228040776427,
 3.1158954808562713,
 3.4052657087292215,
 3.6020831686299313,
 3.886763217809259,
 3.137785513760017,
 4.02542799674907,
 3.7763323885739695,
 3.3337208696256484,
 3.5171952135141558,
 3.6891447831390303,
 3.938581586739063,
 3.699229646403259,
 3.843222070648639,
 4.035733894443033,
 3.7278278596113403,
 3.1963583076093105,
 3.618869111497613,
 3.025696550187967,
 3.1504520407210235,
 3.5682485911988056,
 3.345638726119482,
 3.5756910300264,
 3.3943007794315996,
 3.3038640066205707,
 3.6886888771424227,
 3.340775392522319,
 3.194647108517011,
 3.492434233999642,
 3.3669325499078164,
 3.1265629564709316,
 3.40723034229984,
 3.3941155374735565,
 3.567896699692211,
 3.4910011923031625,
 3.949837241619371,
 3.5433289671733714,
 3.7712970149410325,
 3.7111768054737926,
 4.199530424864681,
 3.2684282199964856,
 3.9264723620827855,
 3.7636813783300402,
 3.676211331640845,
 3.7860046948356807,
 3.566753125,
 3.450768941079345,
 3.5351455413212047,
 3.9509969406454934,
 3.469722598105548,
 4.07384293647425,
 2.7473300376193692,
 3.6082940334166027,
 3.7604096850693343,
 3.866988361373588,
 3.137977494070747,
 3.3230516112306923,
 3.353421813850604,
 3.482678411088828,
 3.8465215418059726,
 3.196469013506455,
 3.794018866502788,
 3.3325332186551053,
 4.129615328037659,
 3.410122309539017,
 2.9695361879361366,
 3.333708453975148,
 3.142681345933455,
 3.656707992094002,
 3.4902903628952195,
 3.416214678110591,
 3.4956161068968896,
 3.60302780763586,
 3.3670808544122846,
 2.718981457919826,
 3.566753125,
 3.3263449746785385,
 3.7305811448338657,
 3.464132643520837,
 3.342609312322707,
 3.309591106086301,
 3.8862620481805163,
 3.831697761980587,
 3.7546601738854095,
 3.5975510341926125,
 3.818208121640372,
 3.1666123188405795,
 3.4339874696047907,
 3.1579743356059145,
 3.845790387681669,
 3.8485371961491195,
 3.566753125,
 3.534577900404966,
 3.0268431768814796,
 3.255501291688048,
 3.751733090470565,
 4.007726476476477,
 3.566753125,
 3.6467399665821083,
 4.212082568261661,
 3.566753125,
 3.7156125663129975,
 3.4930643161913455,
 3.566753125,
 3.6315093600968043,
 3.6133353723962354,
 4.434070745240958,
 3.7879544290834612,
 2.761252643449011,
 3.7860544137782908,
 3.463230383626738,
 3.5198270429621275,
 3.7083361018604926,
 3.7073100454709658,
 3.891507169856603,
 3.489583333333333,
 3.1726911539369214,
 3.1177122345870956,
 2.5705277005867577,
 3.658895574772555,
 3.5775835325296197,
 4.232395560707351,
 3.506555061243356,
 3.4690208870486394,
 3.42522893003704,
 4.042603584394629,
 3.426629996907894,
 3.566753125,
 3.5320200346487995,
 3.848385167464115,
 3.9419493665803627,
 3.502093700132864,
 3.6291202885765443,
 3.9478264510852963,
 3.4738159977466307,
 3.520201958891276,
 3.1554383824298413,
 3.7822252574314477,
 3.332130308933025,
 3.027147280065773,
 3.352858386505874,
 3.465296382345773,
 3.4092259586190865,
 3.783858679953784,
 3.8668114748964273,
 3.9006650226184276,
 3.18947477827051,
 3.2938646676792054,
 3.2060854385340685,
 3.369042804821459,
 2.961942569088127,
 4.302616847872322,
 4.116752877768097,
 3.573760980303233,
 3.5929471494984098,
 4.216816557386733,
 3.7810373838294016,
 2.885510146333576,
 4.156788002258168,
 3.4755859330916774,
 3.8340864939179298,
 4.015525096777877,
 3.1433698080322072,
 4.290629465672802,
 3.6645410413611352,
 3.374494220817952,
 3.9211641313854813,
 3.22158702041145,
 3.301356389399074,
 3.460063839591087,
 3.4088059692500483,
 3.2195533419893074,
 3.7066882842262867,
 3.5025453244019955,
 3.427897959371859,
 3.742398716275728,
 4.336649904214559,
 3.8143370591220576,
 4.133313351163578,
 3.810004809342246,
 3.6053463030874418,
 3.6379212874327207,
 3.676944127904969,
 3.483655695637113,
 3.5419071613180373,
 3.271596670496302,
 3.5810435864228047,
 3.5991710538970083,
 3.63701534815392,
 3.5828384998937057,
 3.4629481693604625,
 3.6255975030405,
 3.641678547255944,
 3.738359156193001,
 3.4285357466319484,
 3.059522906872904,
 3.4085931988735148,
 3.268615285739051,
 3.545589614311985,
 3.8431925892238175,
 3.5814827043800754,
 3.7190465818167002,
 3.248513943741436,
 3.598307748412492,
 3.1357243288718473,
 2.986651824900925,
 4.062455800377171,
 4.08470081388378,
 3.334180322109468,
 3.3061940799688037,
 3.6831753197893153,
 3.71968204552414,
 3.407743738485591,
 3.5346216988729253,
 3.6761049723756907,
 3.722821699585598,
 3.7481284069680045,
 2.9134908340973142,
 3.882163225365331,
 3.0266010086592443,
 2.808860294807728,
 3.3622570615400527,
 3.7337484638739293,
 3.703379342925512,
 2.984073242061718,
 3.884049907732022,
 3.6845824038853054,
 3.4778200336464993,
 3.9844673531862167,
 2.984578214532641,
 3.3736516952543445,
 3.5194388210286007,
 4.137133409912453,
 3.3814798538347612,
 3.4599437699049704,
 3.893754323004902,
 3.566753125,
 3.77028403170225,
 3.2121096239643085,
 3.6239661297617483,
 3.3749173636253667,
 3.1687447169441585,
 3.7195638660914927,
 3.3609640877913183,
 4.086707945905423,
 3.5120652800577172,
 3.344404122103785,
 3.607937661602583,
 3.8733450800202487,
 3.6774463563288293,
 3.170608108108108,
 3.566753125,
 3.7624052973110813,
 3.4318561213244503,
 3.7472350257656633,
 2.971584974326835,
 3.9666674526437724,
 3.7934294586119197,
 3.46108750655603,
 3.3757130823759747,
 3.497338496330432,
 3.0508202265911364,
 3.2649539014352866,
 3.843523892056673,
 3.5810287693047043,
 3.5036366411366413,
 3.9137857853974682,
 3.582994338741683,
 3.2798686491224602,
 3.3528289247689917,
 3.547415734554463,
 3.566753125,
 3.718851589389925,
 3.3688626983129195,
 2.470971192006752,
 3.5746820442634446,
 3.182482932347403,
 3.674725114587633,
 3.870798349808408,
 3.350981182143965,
 4.002404428058023,
 3.840456208306434,
 3.4677753544165757,
 3.4423839662447255,
 3.674862054858184,
 3.175690714245526,
 3.218767485799861,
 3.346854701332304,
 3.35651265203873,
 3.5062770259817753,
 3.566753125,
 3.9273361051010154,
 3.566753125,
 4.01450606041485,
 4.363765548296608,
 3.2284754192564016,
 3.4648634066565793,
 3.5043329580087046,
 3.261838817396045,
 3.442830978545264,
 3.566753125,
 3.8166843372784927,
 3.480944164896741,
 3.686373338233527,
 3.4219377040364938,
 3.614983042635659,
 3.8810644236094083,
 3.532519224456566,
 3.6953645576214305,
 2.82525174002399,
 3.62350328683662,
 3.6566604170477413,
 3.5840951767798703,
 3.4252913588188507,
 3.6142245406415445,
 3.5847116189725656,
 3.56489221979431,
 3.562474492792285,
 3.361147697105445,
 3.3487061834753566,
 4.066089210655423,
 3.7974249294057163,
 3.2840190304264953,
 3.956039057087414,
 3.6426331918906176,
 3.77652188513807,
 3.381372633195526,
 3.5210974191004523,
 4.112893225826156,
 3.6004348834976314,
 4.153269861810787,
 3.197839714805337,
 3.1489583333333333,
 4.170371994035053,
 4.0452354260089685,
 3.258963080178712,
 3.7845691722460546,
 3.566753125,
 2.8969051813156774,
 2.6964901420450764,
 3.681643625192012,
 3.808389166740197,
 3.818451106959979,
 2.8825812971880387,
 3.3193786301300077,
 3.92751812314843,
 2.598934368609407,
 3.1640133216024005,
 3.900321442332425,
 3.3977529874879933,
 3.398969588383028,
 3.5530666474113657,
 3.7175570001884304,
 3.0712346316373162,
 3.332606585465662,
 3.2190598677554627,
 3.5437279062311022,
 3.42227849282268,
 3.4656449983159314,
 3.6143160867553545,
 3.6794544272498615,
 3.7914864501757384,
 2.9352449937976255,
 3.2556029956336703,
 4.1490057184228935,
 3.3615550755939525,
 3.846374245552446,
 3.2065111721444475,
 2.9879583490725556,
 3.330796484530453,
 3.2864119882960976,
 3.8973730354752947,
 3.735834996568289,
 3.588656120580327,
 3.588542731547741,
 3.4978094043030854,
 3.478248480243161,
 3.6775938269341575,
 3.040898224043716,
 2.7179231975648914,
 3.188202991120112,
 3.7400292250803813,
 3.778036382467575,
 3.3345085079967864,
 3.4461448676952267,
 4.0592586326422815,
 3.7937930115109526,
 3.418013545755407,
 3.465759097867955,
 3.790387815673895,
 3.665415374085894,
 3.5773622630331756,
 3.732286474080258,
 4.099567486767703,
 3.2488881687191506,
 4.1146455255417695,
 3.4839143567295503,
 2.555284900057964,
 3.175279122831464,
 3.801786960930335,
 3.504314289534457,
 4.1686336326422815,
 3.143347729562037,
 3.7481797753010957,
 3.5129688968834056,
 3.719281640920432,
 3.8442328090938704,
 3.871674181267335,
 4.017889025218612,
 3.474881608293105,
 2.83629347869494,
 3.2667332949610173,
 3.6725825147779463,
 4.303941312464009,
 3.7325937976714028,
 3.6391352810388025,
 3.4481871304115375,
 3.6381917185609303,
 3.396101366447631,
 3.639066171703383,
 4.01400399277341,
 2.9120431350258937,
 3.922400652750879,
 3.2419935752301727,
 3.4443371697026866,
 2.884256689552443,
 3.4859181562661927,
 3.5173722238521425,
 3.474529265800613,
 3.718071966508903,
 3.561501270907766,
 3.672263589264076,
 3.527825298684394,
 3.351454913626819,
 3.5896985363417544,
 3.9600919157925487,
 3.538253774403291,
 2.963074142655473,
 2.8617404443351226,
 4.180708100390853,
 3.898042684618992,
 2.932332932247316,
 3.3965806353618637,
 3.4638000994790437,
 3.7599349461518896,
 3.4311593228954114,
 3.4215946679673452,
 4.255393512850073,
 3.7889397288249516,
 2.956268115942029,
 3.9411163919506524,
 3.466966820735812,
 3.8725700490739277,
 3.0368335345926116,
 3.6306626578448937,
 2.6565773218672035,
 2.963320753154955,
 3.556773650186847,
 3.0666039912641163,
 3.8094543091547894,
 3.0444424369839913,
 3.714609575259778,
 3.7132927510186517,
 3.6154495596115637,
 4.06923997276459,
 4.1317952117752235,
 3.7387807216860187,
 3.5451571613970536,
 2.945670220445333,
 3.436655103615597,
 4.224932746571538,
 3.9148409808196876,
 3.566853897293619,
 3.525493892450788,
 3.775244325095321,
 4.259636009825502,
 2.968888888888889,
 3.7406723850895602,
 3.929140146157473,
 4.032656366998273,
 3.9829981313032157,
 3.133758776212396,
 3.7208350583034875,
 3.4890012766375333,
 3.1542605465802147,
 4.00581045314693,
 3.6813608569543006,
 3.583639259708738,
 3.6229107882523475,
 3.0082319970520355,
 2.8962690749400535,
 3.2685926350828707,
 3.7148882389881006,
 3.6737953451907734,
 4.00601770056579,
 3.3103260716992784,
 3.8949478203357293,
 4.066407878745205,
 3.7777742397707375,
 3.655966212326968,
 2.3422711571675303,
 3.900531450730665,
 3.8613760661694174,
 4.071371964958947,
 3.5633911039016475,
 3.801701827873173,
 3.620881915157529,
 3.481214120305287,
 3.768243235352509,
 3.566753125,
 3.5421555490189673,
 3.2553071373597096,
 4.236561282838586,
 3.2140009522934916,
 3.8097594222760147,
 3.468770888857507,
 3.616855202661571,
 3.732880711358962,
 3.7781996195530447,
 3.0247454192208485,
 3.188136437946179,
 3.50463474982934,
 3.4628952776470214,
 3.0274724998618083,
 3.5452114766557807,
 3.4666014341347617,
 2.923501135626217,
 3.1786132266253606,
 3.356826769144392,
 2.885010755356995,
 3.503271484602256,
 3.140318508723325,
 3.6461097708082026,
 4.083740446327707,
 3.838603024552106,
 3.79263351194783,
 2.909829640468227,
 3.850365853658537,
 4.128028770333284,
 3.618004478528823,
 3.5127332402107916,
 3.744861085163735,
 2.798379818505616,
 3.6198795436230222,
 3.7844482637837578,
 4.060045808207535,
 3.5713489756842103,
 3.9345786348991894,
 2.854143206854345,
 3.7424714866937903,
 3.5466532432756903,
 3.796894565390951,
 3.830229703926789,
 4.054349954733557,
 4.054126292116248,
 3.441118268425398,
 3.415331767006866,
 3.832203651385295,
 3.6413221327434435,
 3.87333982065452,
 3.740219471842447,
 3.1489896788590954,
 3.236295955259091,
 3.7498542529330896,
 4.012930202413409,
 3.7407214798576938,
 3.2075604560487347,
 3.307209879633498,
 3.42711176068355,
 3.716301138760017,
 3.7945859565445756,
 3.5794079115996924,
 3.854089163997701,
 3.218318935382483,
 3.614835492326069,
 3.6302940699689694,
 3.277919336721541,
 3.430555098819428,
 4.084996438191492,
 3.7877148323092835,
 3.485576503141358,
 3.6771518773268497,
 3.9645954362056552,
 3.0182405174665234,
 3.3657742683701324,
 3.5182244128078892,
 3.3784693669768147,
 3.652329213505782,
 3.65025593689687,
 3.6547153865439044,
 3.2564441760348295,
 3.6863983834925937,
 3.4638544557306665,
 3.7363140943918967,
 3.215310710338591,
 2.4549654792853732,
 3.3808211190957147,
 3.7187524078592524,
 3.9261912887126718,
 3.8308875040516943,
 4.127699676823638,
 4.274988153299944,
 3.8666561477801755,
 3.566753125,
 3.337663191412052,
 3.9426175869190203,
 3.566753125,
 3.919811792204194,
 3.7692703402627274,
 3.986545879009338,
 3.6907767010250705,
 2.9890205496444127,
 3.559976793303119,
 3.3162911640056856,
 2.851130512514899,
 3.0744093123820386,
 3.3753797173501754,
 3.579230044706201,
 3.7607642282097817,
 3.6726251862950594,
 3.59611071625997,
 3.566753125,
 3.5757772841522746,
 3.9372341213260094,
 3.366909672391672,
 3.8600737667127705,
 3.2919785501437593,
 4.148013788706612,
 3.8430494332493703,
 3.0817009338557013,
 3.6467785525664302,
 3.5716532596163924,
 2.828007218333558,
 3.448208696489623,
 3.5968025315486107,
 3.703977740603137,
 3.3532423694361695,
 3.7148705249517704,
 3.4784452093528824,
 3.8302285431716543,
 4.073976737982212,
 3.1542123971874108,
 3.808120083420513,
 3.7288435595395946,
 3.7127873291530835,
 2.641820285463762,
 3.850125533495378,
 3.5580680599650973,
 3.072436285374582,
 4.107148875833174,
 3.9178495431217923,
 3.566753125,
 3.374468954248366,
 3.024215876907469,
 3.519219739585226,
 3.617161298081568,
 3.3636559758786473,
 3.1341931006805677,
 3.925897779598671,
 3.493139306280899,
 3.059961424563725,
 3.566753125,
 4.022892058094332,
 3.2898041449928,
 4.034715955599991,
 3.8819107177738896,
 2.824481929332383,
 3.4465789371190434,
 2.5582326428845414,
 3.0887457515896637,
 3.182924503660041,
 3.5772298536716605,
 3.2284219115588844,
 3.387244978963245,
 3.2126164918536917,
 3.204446693263626,
 3.751213940154094,
 3.5736776950262565,
 3.110144912607896,
 3.882366900364702,
 3.6023909413326614,
 3.834079399121324,
 3.7149206219715936,
 3.7592158403853357,
 3.2036588988199712,
 3.9105543414223938,
 3.8625616231852566,
 3.0156834112149533,
 3.0845499328257953,
 4.047218701978778,
 3.834445141502858,
 3.7556788832861887,
 3.547097804645868,
 3.7237828464692795,
 3.9497348615845724,
 3.751744111623144,
 2.9436392548841432,
 3.97777057853574,
 3.858205169475206,
 3.006779709811147,
 3.197973271177558,
 3.261094385066988,
 3.9235020462974806,
 3.7585532333373504,
 3.5732127406446033,
 3.1874558978125314,
 3.498558576619746,
 3.5487634756129838,
 3.3539611517608043,
 3.507970906765367,
 3.23626400996264,
 3.8135512820512822,
 4.037649890720066,
 3.136222559680615,
 4.204192986176212,
 3.4385862389439907,
 3.2520374490977644,
 2.553133602764599,
 3.1854802464539542,
 3.634418230904348,
 4.171614848700336,
 3.739016947442752,
 3.098057049032549,
 3.724601264628162,
 3.4781778658157925,
 4.068079213505782,
 4.134799620583353,
 3.3909340911686288,
 4.136291584690896,
 3.6944965118433584,
 3.0958963629038165,
 3.495575551338263,
 3.6853676106632727,
 3.9193545556321956,
 4.046853897293619,
 3.159177841331082,
 3.354478537755355,
 3.331687997953061,
 3.707763579329701,
 3.419701670851384,
 3.8833333333333333,
 3.7752790529795623,
 3.793558791048592,
 4.116071769425051,
 3.6758079482398793,
 3.070197792229756,
 3.928394649538406,
 2.9869916793077422,
 3.502692833713298,
 3.4326729284584374,
 3.8209519888928516,
 3.22753168197018,
 3.980556059095441,
 3.637005815027905,
 3.5007080278235803,
 3.784228532329798,
 3.76921059533176,
 3.1809805456412024,
 2.8702880929654713,
 3.566753125,
 4.050777529623027,
 3.8242334570618812,
 3.3223269918060163,
 3.9556220365771058,
 3.8769471663648547,
 3.7650772068017004,
 3.285538474493553,
 3.727889686080852,
 3.141214535202225,
 3.8240233402120545,
 3.713766898581415,
 3.566753125,
 3.7883825016260633,
 3.9488737436989645,
 3.663244754285995,
 3.6455705311637514,
 3.7070401064242136,